name: Flutter Build (Android)

on:
  workflow_call:
    inputs:
      flutter_version:
        description: "Flutter version to use"
        required: false
        default: "stable"
        type: string
      apk_name:
        description: "Name of the output APK file"
        required: false
        default: "app-release.apk"
        type: string
    secrets:
      github_x_token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ”§ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.flutter_version }}

      - name: ğŸ“¦ Install dependencies
        run: flutter pub get

      - name: ğŸ§ª Run analyzer
        run: flutter analyze

      - name: ğŸ› ï¸ Build APK
        run: flutter build apk --release

      - name: ğŸ“ Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/${{ inputs.apk_name }}

      - name: ğŸ“¢ Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/${{ inputs.apk_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_x_token }}
